### ISSUE TITLE
No belief list file: facet-test-00.belief

### ISSUE THREAD

**Issue by murphywonsick** [ScazLab/task-models#1] opened 2017-06-12 22:06 UTC
When trying to generate the policy from the ICRA paper [Roncone2017] (python script icra_scenario2pomdp.py), it fails on the POMDP due to no "facet-test-00.belief" file. How should this file be generated?
```[Initializing POMDP ... done.]
[Finite Grid Method:]
    [Creating grid ... ** Error: The belief list file: facet-test-00.belief does not exist.
done.]

** ABORT ** File: ../../src/belief.c function: sizeBeliefList, Line: 380
	List is NULL.
Traceback (most recent call last):
  File "icra_scenario2pomdp.py", line 18, in <module>
    gp = p.solve(method='grid', n_iterations=500, verbose=True)
  File "/home/murphy/ScazLab/src/task-models/task_models/lib/pomdp.py", line 371, in solve
    stdout=None if verbose else DEVNULL)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/bin/pomdp-solve', '-horizon', '500', '-rand_seed', '9400528733', '-method', 'grid', '-fg_type', 'simplex', '-o', 'tosolve', '-pomdp', '/tmp/tmprO6wS1/tosolve.pomdp']' returned non-zero exit status 255
```

**Comment by omangin** [comment] 2017-06-13 13:58
Hi @murphywonsick. Thanks for reporting the issue. It seems that this is caused by the `pomdp-solve` executable. The `facet-test-00.belief` file is apperently something that it needs to generate internally. Could you tell use on which platform you're running the code and try to run `pomdp-solve` manually against the attached file?

You should be able to do it the following way, from the directory were you'll have placed the attached `tosolve.pomdp`:

```
/usr/local/bin/pomdp-solve -horizon 500 -method grid -fg_type simplex -o tosolve -pomdp tosolve.pomdp
```

If it still does not work, can you run the following instead?
```
/usr/local/bin/pomdp-solve -horizon 10 -o tosolve -pomdp tosolve.pomdp
```

Note: I could only attach the file as `.TXT` so you'll need to rename it as a `.pomdp`.

[tosolve.TXT](https://github.com/ScazLab/task-models/files/1071638/tosolve.TXT)

**Comment by murphywonsick** [comment] 2017-06-13 16:43
I'm on Ubuntu 14.04.
The first suggestion did not work, it throws the exact same error as before. The second suggestion finds a solution though and provides the .alpha and .pg files.

From what I found, the `facet-test-00.belief` is read from `finite-grid.c` in the pomdp-solve-5.4 code. However, I have been unable to figure out yet how/when that file is generated so I was hoping that I was just missing something on my end. I tried to self generate the file by creating an empty file with the proper name, but that only replaces the "does not exist" error with a "file format incorrect".

**Comment by omangin** [comment] 2017-06-14 19:49
OK. Sorry to come back so late on it. Actually this is a bug in the solver `pomdp-solve` that is used by the code. It has been fixed on this repository: [github.com/cmansley/pomdp-solve](https://github.com/cmansley/pomdp-solve). I forgot that I had switched to this version on the code so that's why you were having the issue.

The solution is to compile pomdp-solve from this version. I'll update the README accordingly. Sorry for the wrong documentation and thanks again for the notice!

**Closed as completed** 2017-06-14 19:53 UTC
